### PR TITLE
fixing split percentage rounding issue

### LINKED ISSUE #62: lenient mode
Trying to import a >400.000 line QIF file there are quite a few detail errors to be expected. I already ran in the "S" problem and the next one is:
```
pydantic.error_wrappers.ValidationError: 1 validation error for Transaction
splits
  Split percentages cannot exceed 100% of the transaction (type=value_error)
```

it would be great to have a lenient mode where the parser tries to continue if if errors are present.

### PR DESCRIPTION
**Pull request by patlachance**
Fixes #62/#63

### CODE REVIEW

**Comment by isaacharrisholt** [comment]
Looks good! I'll merge once you've got tests passing

**Review by isaacharrisholt — APPROVED** [review]

**Comment by isaacharrisholt** [comment]
Please make sure to test with `tox` on your own machine :)

Also, it might be easier if you run `poetry run pre-commit install` to automatically run `black` etc. when you commit

**Comment by patlachance** [comment]
> Please make sure to test with `tox` on your own machine :)

It's done but I'm running python 3.12 and the tox test was failing only on python 3.8.
As there is no entry for tox in the makefile, I didn't think to run it. Now all tox tests pass for all of your configured python versions 

> Also, it might be easier if you run `poetry run pre-commit install` to automatically run `black` etc. when you commit

Thanks for the hint!

**Comment by patlachance** [comment]
@isaacharrisholt anything else missing before merging?

**Comment by isaacharrisholt** [comment]
Hey @patlachance my apologies for the delay. Assuming all the tests pass, I'll get it merged and released!

**Pull request merged**
