### PR TITLE
Fixed bug with export of CCard charge transaction to qif - specifically one with splits

### PR DESCRIPTION
**Pull request by sweenip**
Tested with Quicken Home, Business & Rental Property R37.66 Build 27.1.37.66

Identified and resolved the following issues:
1. For a CCard charge transaction that has splits, split values show up as positive whereas charge value is negative. This was causing a ValueError 'Splits amounts cannot sum to more than Transaction amount'  to be raised. Made required changes in quiffen/core/transactions.py

2. The latest version of quick is not loading memo's correctly for splits from the exported qif file. quicken seems to be sensitive to the order in which the entries appear in qif file. Requires S -> E ->$ instead of S -> $ -> E. In the latter case the Memo is applied to the next entry. Refer changes in quiffen/core/qif.py

### CODE REVIEW

**Comment by isaacharrisholt** [comment]
@sweenip 
Thank you for bringing this to my attention. Could you please explain the rationale behind the .gitignore changes? Especially those completely unrelated, such as Django, Flask, etc.

**Comment by sweenip** [comment]
@isaacharrisholt the .gitignore file is the standard template from GitHub when you create a new python repo. git was committing pycache too and hence I just used this specific .gitignore. Feel free to completely ignore .gitignore.

**Comment by isaacharrisholt** [comment]
@sweenip could you provide the QIF file you used for testing? Feel free to remove any sensitive information and any non-relevant transactions. I just need the transaction that's causing the issue, and any other useful lines.

**Comment by sweenip** [comment]
@isaacharrisholt , attached is the QIF file
[output.zip](https://github.com/isaacharrisholt/quiffen/files/7843451/output.zip)

**Comment by isaacharrisholt** [comment]
May I also have a snippet of the code that you're using to test this?
@sweenip

**Comment by sweenip** [comment]
Here you go
[quiffen_PR14_upstream.zip](https://github.com/isaacharrisholt/quiffen/files/7848095/quiffen_PR14_upstream.zip)
.

**Comment by isaacharrisholt** [comment]
This has been fixed as of Quiffen v1.2.1. Thanks for your help!

**Pull request closed without merging**
